# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpGY6v11EKDtyi725PMEJitikS-HElSI
"""

from sklearn import datasets
import matplotlib.pyplot as plt

digits = datasets.load_digits() # digits degiskenenine dataset yuklenir.
 
# Display the last digit
plt.figure(-1,figsize=(5, 5))  #plt.figure(num=None, figsize(x,x)) num=sekil icin benzersiz bir tanimlayici figsize=genislik ve uzunluk
plt.imshow(digits.images[-1], cmap=plt.cm.gray_r, interpolation="nearest") #plt.imshow --> digits.image ile skaler goruntu iceren degeri alir , cmap = skaler verileri renklere gore eslesmesi icin kullanilir , 
#interpolation --> ara deger hesabinin yapilmasi icin verilen degere gore figure'un ekranda goruntulenmesine yadimci olur. Desteklenen degiskenler ; 'none', 'antialiased', 'nearest', 'bilinear', 'bicubic', 'spline16', 'spline36', 'hanning', 'hamming', 'hermite', 'kaiser', 'quadric', 'catrom', 'gaussian', 'bessel', 'mitchell', 'sinc', 'lanczos', 'blackman'.
plt.show()
plt.imshow(digits.images[-2], cmap=plt.cm.gray_r, interpolation="nearest")
plt.figure(1, figsize=(5,5))
plt.show()
plt.imshow(digits.images[-3], cmap=plt.cm.gray_r, interpolation="bicubic") #bicubic kullanimindan sonra figure blurlu bir sekilde ekrana getirilir.
plt.figure(1, figsize=(5,5))
plt.show()

plt.imshow(digits.images[-4], cmap=plt.cm.gray_r, interpolation="nearest")
plt.figure(1,figsize=(5,5))
plt.show()