# -*- coding: utf-8 -*-
"""Pandas DataFrame UltraQuick Tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/google/eng-edu/blob/master/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb

## Import NumPy and pandas modules

Run the following code cell to import the NumPy and pandas modules.
"""

import numpy as np
import pandas as pd

my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]]) # np.array fonk. ile 5x2 olcusunde array olusturur.
print(my_data)

my_column_names = ['temperature', 'activity'] # fonk. kullanmadan liste olusturulur ve sutun isimleri tutulur.
print(my_column_names)
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names) #pd.DataFrame ile data degiskenine array atanir columns degiskenine sutun isimlerini tutan liste atanir.
print(my_dataframe)

my_dataframe["adjusted"] = my_dataframe["activity"] + 2 # yeni sutun ismi eklendi.
print(my_dataframe)

print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

#TASK
my_column_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

my_data = np.random.randint(low=0, high=101, size=(3, 4))

df = pd.DataFrame(data=my_data, columns=my_column_names)

# Tum dataframe'i ekrana getirir.
print(df)

print("\nSecond row of the Eleanor column: %d\n" % df['Eleanor'][1])

df['Janet'] = df['Tahani'] + df['Jason']

# Degistirilmis dataframe'i ekrana getirir.
print(df)