# -*- coding: utf-8 -*-
"""PCA-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KUz_VXyV6AGL18mzs1plwSVwc19lEeS
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# %matplotlib inline

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data" # url oalrak iris data setin yüklenmesi
# loading dataset into Pandas DataFrame
df = pd.read_csv(url
                 , names=['sepal length','sepal width','petal length','petal width','target']) # url üzerinden indirilen dataseti verilen sütün isimleri halinde görselleştirilmesi

df.head() # DataFrame.head() = Bu işlev, konuma dayalı olarak nesne için ilk n satırı döndürür. Nesnenizin içinde doğru türde veri olup olmadığını hızlı bir şekilde test etmek için kullanışlıdır.

# Standardize the Data
features = ['sepal length', 'sepal width', 'petal length', 'petal width']
x = df.loc[:, features].values

y = df.loc[:,['target']].values

x = StandardScaler().fit_transform(x)

pd.DataFrame(data = x, columns = features).head()

# PCA Projection to 2D 
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

principalDf.head(5) # ilk 5 sütunu geri döndürür

df[['target']].head() # DataFrame içinde bulunan target sütunun döndürür

finalDf = pd.concat([principalDf, df[['target']]], axis = 1)
finalDf.head(5)

# Visualize 2D Projection
# Verisetinin 2D boyutta görselleştirme kodu
fig = plt.figure(figsize = (8,8))
ax = fig.add_subplot(1,1,1) 
ax.set_xlabel('Principal Component 1', fontsize = 15)
ax.set_ylabel('Principal Component 2', fontsize = 15)
ax.set_title('2 Component PCA', fontsize = 20)


targets = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
colors = ['r', 'g', 'b']
for target, color in zip(targets,colors):
    indicesToKeep = finalDf['target'] == target
    ax.scatter(finalDf.loc[indicesToKeep, 'principal component 1']
               , finalDf.loc[indicesToKeep, 'principal component 2']
               , c = color
               , s = 50)
ax.legend(targets)
ax.grid()

pca.explained_variance_ratio_ # # explained_varience_ratio = Seçilen bileşenlerin her biri tarafından açıklanan varyans yüzdesi